CREATE TABLE student (
  studentid       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  registrationnumber  BIGINT      NOT NULL UNIQUE,
  studentname     VARCHAR(255)
);

CREATE TABLE subject (
  subjectid   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subjectname         VARCHAR(100) NOT NULL
);

CREATE TABLE score (
  studentid BIGINT NOT NULL REFERENCES student(studentid),
  subjectid BIGINT NOT NULL REFERENCES subject(subjectid),
  score DOUBLE PRECISION NOT NULL,
  PRIMARY KEY(studentid, subjectid)
);


