version: '1.0'
services:
  gscore_spring_app:
    image: 'gscore_spring_app:latest'
    build: .
    container_name: gscore_spring_app
    ports:
      - "8080:8080"
    develop:
      watch:
        - action: rebuild
          path: ./src
        - action: rebuild
          path: ./pom.xml
    volumes:
      - ./src:/app/src
      - ./target:/app/target
      - ./logs:/app/logs
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/gscore
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Ngocquynguyen1
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_FLYWAY_ENABLED=true
      - SPRING_FLYWAY_BASELINE-ON-MIGRATE=true
      - SPRING_FLYWAY_LOCATIONS=classpath:db/migration

    depends_on:
      db:
        condition: service_healthy
    networks:
      - gscore

  db:
    image: 'postgres:15'
    container_name: db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Ngocquynguyen1
      - POSTGRES_DB=gscore
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - gscore


 
volumes:
  postgres-data:

networks:
  gscore:
    driver: bridge
